# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Comerciante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoComerciante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.Comerciante')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('identificador', models.CharField(max_length=32)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.Cliente')),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.Comerciante')),
                ('endereco_comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EnderecoComerciante')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.Produto')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enderecocomerciante',
            unique_together=set([('comerciante', 'endereco')]),
        ),
    ]
